// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       int    `json:"id"`
	TopicID  int    `json:"topicId"`
	ParentID *int   `json:"parentId,omitempty"`
	Text     string `json:"text"`
	UserID   string `json:"userId"`
	IssuedAt string `json:"issuedAt"`
}

type Mutation struct {
}

type NewComment struct {
	ParentID *int   `json:"parentId,omitempty"`
	Text     string `json:"text"`
	UserID   int    `json:"userId"`
	IssuedAt string `json:"issuedAt"`
}

type NewTopic struct {
	Header   string `json:"header"`
	Text     string `json:"text"`
	UserID   int    `json:"userId"`
	IssuedAt string `json:"issuedAt"`
}

type NewUser struct {
	UserID   int    `json:"userId"`
	Name     string `json:"name"`
	Login    string `json:"login"`
	Password string `json:"password"`
}

type PaginationTopics struct {
	Offset int `json:"offset"`
	Limit  int `json:"limit"`
}

type Query struct {
}

type Topic struct {
	ID       int    `json:"id"`
	UserID   int    `json:"userId" db:"user_id"`
	Text     string `json:"text"`
	Header   string `json:"header"`
	IssuedAt string `json:"issuedAt"`
}

type User struct {
	ID       int    `json:"id"`
	Login    string `json:"login"`
	Password string `json:"password"`
	Name     string `json:"name"`
}
